language: node_js
node_js: node
deploy: sleepy-stream-77603
  provider: heroku
  api_key:
    secure: CMeSDSncKkNxEZII3XoxToPtzW2x+6CWrzT8xp4ydHlVehMjoA6zqfljySoNnwqLpu5KKU2QGHIkIkDethLwiwud/asmtPpLfDfU0dFu9MfRX4ELt8fTbrz1mRphzAB9TDDA9h5DBCGcYZNp2thdP5p/ny+XEnV90HKb4vCB1ZF1PFyOD2/nO9l7PuQKAiMhlX88x3lCSz8g4L1I6iJ7oKjNfzaQxruWBsbfjnqTpD7fVMyQyGT3hlNjSLP8Kqq3jeOFK5dIJZJCzGz10VRmuJ0L9CQA3phIrZXc606HWychUtih8SGqZPJ277t/NuYHjWStwT+jQ8qmVYbXkDPPz2LJRCnW/4PqdsUFs/ltQ+0um2PAzgWDNCk4guhYdixgNYpIUBGX0hV9vMOa1Q8LJVuLxJD0vpuB8HygJmO3Y2ngMWpTRoXb94KHjE+XMvQiyxxhHW3xGREXgFfIaLj2ie5Jy1uX9bBAz8Z9BmYz5m6eZlYcKzCgaGAjIlv+cMBUJ6xHQW5WmfocEguhTdRdSrBAvJ6o+GXr/Lx191tStbFUvWxZdeQnoIjNIF5R6P6YwdqGVFdD7xx+fXJUS/3CRvrnIpjPQ6sfWH69UPC4087a1CtRImLlP4MkkwpPgZ2FqBQqJRDet8baEnJzkw8eYEWhPXS4Hmma9E+A7rdDOaI=
  app: node-shopping-list-integration-tests
  on:
    repo: dadsocks/node-shopping-list-integration-tests
